### PR TITLE
Comment popup window

### LINKED ISSUE #14: [4pt]  -Display Comments pop up with selected item's details - Student B
Create a comments popup only with the top section (displaying details of the selected item)

Screenshot 2021-06-27 at 22 10 45

When the popup loads, the webapp retrieves data from the selected API and shows details about the selected item.

Add event to button prepared by your teammate that will open your popup. You need to communicate with your team member to make sure that you do not block each other (most likely the easiest solution is to merge the list of items feature to the dev branch before you try to add that event).

### PR DESCRIPTION
**Pull request by chiztechnology**
### Highlights

1. The comments popup window.
2. Item details
3. Form for adding comments.

Kindly use this comment popup and make it dynamic by displaying data according to the selected Item.
If there's anything that needs improvement in the design ; kindly let us know

Faithfully 🎊

### CODE REVIEW

**Comment by rashedarman** [comment]
# Status: Approved 🟢 

Hi, @chiztechnology 

Your project is complete! There is nothing else to say other than... it's time to merge it 💯 

- [ ] Linter checks passed ✔️ 
- [ ] Clean code✔️ 
- [ ] Comment pop-up was created according to wireframe ✔️ 

## **Optional suggestions (highly recommend)**
- Your popup looks much thinner than it is in wireframe.
> Try using a fluid width and fixed max-width on the pop-up, it should be wide enough to cover half of the viewport but not exceed a certain width.
image
- The navbar links are aligned to very left as the screen size grows. Please add `margin: auto`  and adjust logo padding accordingly to center your navbar.  
- **Important:** add `z-index: 1` or more to your header. Otherwise absolutely positioned elements and page icons are visible on top of navbar when scrolling.

Let me know if you have any questions.

Cheers and Happy coding!👏👏👏

**Review by ghost — APPROVED** [review]
# Status: Changes required :yellow_circle: 

Hi, @chiztechnology 

Good job so far! I know you have worked hard on making this milestone But There are some issues that you still need to work on but you are almost there!

## Required Changes ♻️
- Your code does not satisfy this part of the requirement:
  > Add event to button prepared by your teammate that will open your popup. 
- Please hide the popup by default and show it only when button was clicked.
- Your popup looks much thinner than it is in wireframe.
> Try using a fluid width and fixed max-width on the pop-up, it should be wide enough to cover half of the viewport but not exceed a certain width.
image

## **Optional suggestions (highly recommend)**

- The navbar links are aligned to very left as the screen size grows. Please add `margin: auto`  and adjust logo padding accordingly to center your navbar.  
- **Important:** add `z-index: 1` or more to your header. Otherwise absolutely positioned elements and page icons are visible on top of navbar when scrolling.

Let me know if you have any questions.

Cheers and Happy coding!👏👏👏

**Review by ghost — CHANGES_REQUESTED** [review]
# Status: Changes required :yellow_circle: 

Hi, @chiztechnology 

Good job so far! I know you have worked hard on making this milestone But There are some issues that you still need to work on but you are almost there!

## Required Changes ♻️
- Your code does not satisfy this part of the requirement:
  > Add event to button prepared by your teammate that will open your popup. 
- Please hide the popup by default and show it only when button was clicked.
- Your popup looks much thinner than it is in wireframe.
> Try using a fluid width and fixed max-width on the pop-up, it should be wide enough to cover half of the viewport but not exceed a certain width.
image

## **Optional suggestions (highly recommend)**

- The navbar links are aligned to very left as the screen size grows. Please add `margin: auto`  and adjust logo padding accordingly to center your navbar.  
- **Important:** add `z-index: 1` or more to your header. Otherwise absolutely positioned elements and page icons are visible on top of navbar when scrolling.

Let me know if you have any questions.

Cheers and Happy coding!👏👏👏

**Comment by chiztechnology** [comment]
thank you for your great review.
I'm working accordingly.
Once I'll be done ;  I'll commit the changes and share the same link with you for another review 🤝 ✔️

**Comment by chiztechnology** [comment]
the code is ready.
Kindly add the dynamic comments and comment total

**Review by HunterX-7 — APPROVED** [review]
# Status: Approved 🟢 

Hi, @chiztechnology  

Your project is complete! There is nothing else to say other than... it's time to merge it 💯 

- Add the comments popup window dinamically✔️
- Display details stored in the API ✔️ 
- Form adds and displays new comments and stores them in the API ✔️ 
- Linters pass ✔️ 
- Descriptive commit messages ✔️

Keep up the good work have a great day! 😄

**Pull request merged**
